package tp_hibernate_new;
// Generated 20 mars 2017 10:37:11 by Hibernate Tools 4.3.1



/**
 * Entreprise generated by hbm2java
 */
public class Entreprise  implements java.io.Serializable {


     private Integer idEntreprise;
     private String nomEnt;
     private String listeActivites;
     private int nbEmployes;

    public Entreprise() {
    }

    public Entreprise(String nomEnt, String listeActivites, int nbEmployes) {
       this.nomEnt = nomEnt;
       this.listeActivites = listeActivites;
       this.nbEmployes = nbEmployes;
    }
   
    public Integer getIdEntreprise() {
        return this.idEntreprise;
    }
    
    public void setIdEntreprise(Integer idEntreprise) {
        this.idEntreprise = idEntreprise;
    }
    public String getNomEnt() {
        return this.nomEnt;
    }
    
    public void setNomEnt(String nomEnt) {
        this.nomEnt = nomEnt;
    }
    public String getListeActivites() {
        return this.listeActivites;
    }
    
    public void setListeActivites(String listeActivites) {
        this.listeActivites = listeActivites;
    }
    public int getNbEmployes() {
        return this.nbEmployes;
    }
    
    public void setNbEmployes(int nbEmployes) {
        this.nbEmployes = nbEmployes;
    }




}


