package tp_hibernate3_new;
// Generated 28 mars 2017 20:06:31 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Clients generated by hbm2java
 */
public class Clients  implements java.io.Serializable {


     private int numero;
     private Pays pays;
     private String nom;
     private String adresse;
     private String ville;
     private String tel;
     private Set reservationses = new HashSet(0);

    public Clients() {
    }

	
    public Clients(int numero) {
        this.numero = numero;
    }
    public Clients(int numero, Pays pays, String nom, String adresse, String ville, String tel, Set reservationses) {
       this.numero = numero;
       this.pays = pays;
       this.nom = nom;
       this.adresse = adresse;
       this.ville = ville;
       this.tel = tel;
       this.reservationses = reservationses;
    }
   
    public int getNumero() {
        return this.numero;
    }
    
    public void setNumero(int numero) {
        this.numero = numero;
    }
    public Pays getPays() {
        return this.pays;
    }
    
    public void setPays(Pays pays) {
        this.pays = pays;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }
    public String getVille() {
        return this.ville;
    }
    
    public void setVille(String ville) {
        this.ville = ville;
    }
    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }
    public Set getReservationses() {
        return this.reservationses;
    }
    
    public void setReservationses(Set reservationses) {
        this.reservationses = reservationses;
    }




}


