package tp_hibernate3_new;
// Generated 28 mars 2017 20:06:31 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Compagniesaeriennes generated by hbm2java
 */
public class Compagniesaeriennes  implements java.io.Serializable {


     private int numero;
     private Pays pays;
     private String nom;
     private Set volses = new HashSet(0);

    public Compagniesaeriennes() {
    }

	
    public Compagniesaeriennes(int numero) {
        this.numero = numero;
    }
    public Compagniesaeriennes(int numero, Pays pays, String nom, Set volses) {
       this.numero = numero;
       this.pays = pays;
       this.nom = nom;
       this.volses = volses;
    }
   
    public int getNumero() {
        return this.numero;
    }
    
    public void setNumero(int numero) {
        this.numero = numero;
    }
    public Pays getPays() {
        return this.pays;
    }
    
    public void setPays(Pays pays) {
        this.pays = pays;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public Set getVolses() {
        return this.volses;
    }
    
    public void setVolses(Set volses) {
        this.volses = volses;
    }




}


