package tp_hibernate3_new;
// Generated 28 mars 2017 20:06:31 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Pays generated by hbm2java
 */
public class Pays  implements java.io.Serializable {


     private int numero;
     private String nom;
     private Set aeroports = new HashSet(0);
     private Set clientses = new HashSet(0);
     private Set compagniesaerienneses = new HashSet(0);
     private Set passagerses = new HashSet(0);

    public Pays() {
    }

	
    public Pays(int numero) {
        this.numero = numero;
    }
    public Pays(int numero, String nom, Set aeroports, Set clientses, Set compagniesaerienneses, Set passagerses) {
       this.numero = numero;
       this.nom = nom;
       this.aeroports = aeroports;
       this.clientses = clientses;
       this.compagniesaerienneses = compagniesaerienneses;
       this.passagerses = passagerses;
    }
   
    public int getNumero() {
        return this.numero;
    }
    
    public void setNumero(int numero) {
        this.numero = numero;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public Set getAeroports() {
        return this.aeroports;
    }
    
    public void setAeroports(Set aeroports) {
        this.aeroports = aeroports;
    }
    public Set getClientses() {
        return this.clientses;
    }
    
    public void setClientses(Set clientses) {
        this.clientses = clientses;
    }
    public Set getCompagniesaerienneses() {
        return this.compagniesaerienneses;
    }
    
    public void setCompagniesaerienneses(Set compagniesaerienneses) {
        this.compagniesaerienneses = compagniesaerienneses;
    }
    public Set getPassagerses() {
        return this.passagerses;
    }
    
    public void setPassagerses(Set passagerses) {
        this.passagerses = passagerses;
    }




}


