package tp_hibernate3_new;
// Generated 28 mars 2017 20:06:31 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Reservations generated by hbm2java
 */
public class Reservations  implements java.io.Serializable {


     private int numero;
     private Clients clients;
     private Passagers passagers;
     private Vols vols;
     private Date dateReservation;
     private Date dateDepart;

    public Reservations() {
    }

	
    public Reservations(int numero) {
        this.numero = numero;
    }
    public Reservations(int numero, Clients clients, Passagers passagers, Vols vols, Date dateReservation, Date dateDepart) {
       this.numero = numero;
       this.clients = clients;
       this.passagers = passagers;
       this.vols = vols;
       this.dateReservation = dateReservation;
       this.dateDepart = dateDepart;
    }
   
    public int getNumero() {
        return this.numero;
    }
    
    public void setNumero(int numero) {
        this.numero = numero;
    }
    public Clients getClients() {
        return this.clients;
    }
    
    public void setClients(Clients clients) {
        this.clients = clients;
    }
    public Passagers getPassagers() {
        return this.passagers;
    }
    
    public void setPassagers(Passagers passagers) {
        this.passagers = passagers;
    }
    public Vols getVols() {
        return this.vols;
    }
    
    public void setVols(Vols vols) {
        this.vols = vols;
    }
    public Date getDateReservation() {
        return this.dateReservation;
    }
    
    public void setDateReservation(Date dateReservation) {
        this.dateReservation = dateReservation;
    }
    public Date getDateDepart() {
        return this.dateDepart;
    }
    
    public void setDateDepart(Date dateDepart) {
        this.dateDepart = dateDepart;
    }




}


