package tp_hibernate3_new;
// Generated 28 mars 2017 20:06:31 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Vols generated by hbm2java
 */
public class Vols  implements java.io.Serializable {


     private int numero;
     private Aeroport aeroportByAeroportDepart;
     private Aeroport aeroportByAeroportArrivee;
     private Compagniesaeriennes compagniesaeriennes;
     private String jour;
     private Date heureDepart;
     private Date duree;
     private Integer capacite;
     private Set reservationses = new HashSet(0);
     private Set escaleses = new HashSet(0);

    public Vols() {
    }

	
    public Vols(int numero) {
        this.numero = numero;
    }
    public Vols(int numero, Aeroport aeroportByAeroportDepart, Aeroport aeroportByAeroportArrivee, Compagniesaeriennes compagniesaeriennes, String jour, Date heureDepart, Date duree, Integer capacite, Set reservationses, Set escaleses) {
       this.numero = numero;
       this.aeroportByAeroportDepart = aeroportByAeroportDepart;
       this.aeroportByAeroportArrivee = aeroportByAeroportArrivee;
       this.compagniesaeriennes = compagniesaeriennes;
       this.jour = jour;
       this.heureDepart = heureDepart;
       this.duree = duree;
       this.capacite = capacite;
       this.reservationses = reservationses;
       this.escaleses = escaleses;
    }
   
    public int getNumero() {
        return this.numero;
    }
    
    public void setNumero(int numero) {
        this.numero = numero;
    }
    public Aeroport getAeroportByAeroportDepart() {
        return this.aeroportByAeroportDepart;
    }
    
    public void setAeroportByAeroportDepart(Aeroport aeroportByAeroportDepart) {
        this.aeroportByAeroportDepart = aeroportByAeroportDepart;
    }
    public Aeroport getAeroportByAeroportArrivee() {
        return this.aeroportByAeroportArrivee;
    }
    
    public void setAeroportByAeroportArrivee(Aeroport aeroportByAeroportArrivee) {
        this.aeroportByAeroportArrivee = aeroportByAeroportArrivee;
    }
    public Compagniesaeriennes getCompagniesaeriennes() {
        return this.compagniesaeriennes;
    }
    
    public void setCompagniesaeriennes(Compagniesaeriennes compagniesaeriennes) {
        this.compagniesaeriennes = compagniesaeriennes;
    }
    public String getJour() {
        return this.jour;
    }
    
    public void setJour(String jour) {
        this.jour = jour;
    }
    public Date getHeureDepart() {
        return this.heureDepart;
    }
    
    public void setHeureDepart(Date heureDepart) {
        this.heureDepart = heureDepart;
    }
    public Date getDuree() {
        return this.duree;
    }
    
    public void setDuree(Date duree) {
        this.duree = duree;
    }
    public Integer getCapacite() {
        return this.capacite;
    }
    
    public void setCapacite(Integer capacite) {
        this.capacite = capacite;
    }
    public Set getReservationses() {
        return this.reservationses;
    }
    
    public void setReservationses(Set reservationses) {
        this.reservationses = reservationses;
    }
    public Set getEscaleses() {
        return this.escaleses;
    }
    
    public void setEscaleses(Set escaleses) {
        this.escaleses = escaleses;
    }




}


