package tp_hibernate;
// Generated 27 févr. 2017 10:14:54 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Groupes generated by hbm2java
 */
public class Groupes  implements java.io.Serializable {


     private Integer idgroupe;
     private String nomgroupe;
     private String commentairegroupe;
     private Set grpperses = new HashSet(0);

    public Groupes() {
    }

    public Groupes(String nomgroupe, String commentairegroupe, Set grpperses) {
       this.nomgroupe = nomgroupe;
       this.commentairegroupe = commentairegroupe;
       this.grpperses = grpperses;
    }
   
    public Integer getIdgroupe() {
        return this.idgroupe;
    }
    
    public void setIdgroupe(Integer idgroupe) {
        this.idgroupe = idgroupe;
    }
    public String getNomgroupe() {
        return this.nomgroupe;
    }
    
    public void setNomgroupe(String nomgroupe) {
        this.nomgroupe = nomgroupe;
    }
    public String getCommentairegroupe() {
        return this.commentairegroupe;
    }
    
    public void setCommentairegroupe(String commentairegroupe) {
        this.commentairegroupe = commentairegroupe;
    }
    public Set getGrpperses() {
        return this.grpperses;
    }
    
    public void setGrpperses(Set grpperses) {
        this.grpperses = grpperses;
    }




}


