package tp_hibernate;
// Generated 27 f�vr. 2017 10:14:54 by Hibernate Tools 4.3.1

/**
 * Grppers generated by hbm2java
 */
public class Grppers  implements java.io.Serializable {


     private Integer idgrppers;
     private Groupes groupes;
     private Personnes personnes;

    public Grppers() {
    }

    public Grppers(Groupes groupes, Personnes personnes) {
       this.groupes = groupes;
       this.personnes = personnes;
    }
   
    public Integer getIdgrppers() {
        return this.idgrppers;
    }
    
    public void setIdgrppers(Integer idgrppers) {
        this.idgrppers = idgrppers;
    }
    public Groupes getGroupes() {
        return this.groupes;
    }
    
    public void setGroupes(Groupes groupes) {
        this.groupes = groupes;
    }
    public Personnes getPersonnes() {
        return this.personnes;
    }
    
    public void setPersonnes(Personnes personnes) {
        this.personnes = personnes;
    }




}


